### ISSUE TITLE
Error Accessor

### ISSUE THREAD

**Issue by frodonic** [iamartyom/ngx-flag-picker#10]
**ngx-flag-picker.component.d.ts**
```

set isShowListCountryFlags(value: boolean);
get isShowListCountryFlags(): boolean;
```

> ERROR in node_modules/ngx-flag-picker/lib/ngx-flag-picker/ngx-flag-picker.component.d.ts(6,9): error TS1086: An accessor cannot be declared in an ambient context.
>     node_modules/ngx-flag-picker/lib/ngx-flag-picker/ngx-flag-picker.component.d.ts(7,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by iamartyom** [comment]
Please add an additional details about your environment.
