### ISSUE TITLE
                  Package "ngx-flag-picker" has an incompatible peer dependency to "@angular/common" (requires "^9.0.0" (extended), would install "11.2.9").

### ISSUE THREAD

**Issue by victoriaunizhona** [iamartyom/ngx-flag-picker#12]
It seems that it is not compatible with the latest Angular 11.

Please update it.

**Comment by iamartyom** [comment]
Hi Victoria.

For Angular 11 you can use latest 11.1.1 version.

First number in version contains Angular version e.g. 8.0.0 - for Angular 8.

List with current versions - https://www.npmjs.com/package/ngx-flag-picker

For install latest version use this command:

npm:
```
npm install ngx-flag-picker
```

yarn:
```
yarn add ngx-flag-picker
```

Please try and after this notify me about result if it possible.

Thank you for your feedback.

**Comment by victoriaunizhona** [comment]
Yep, thanks. It seems that I was not using the latest version available.

**Comment by iamartyom** [comment]
Got it. Glad to help.

**Comment by iamartyom** [comment]
Got it. Glad to help.

**Comment by iamartyom** [comment]
Got it. Glad to help.
